# Generated by Django 3.0.4 on 2020-04-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('idNum', models.PositiveIntegerField(max_length=7)),
                ('dateBirth', models.DateTimeField()),
                ('dateConfi', models.DateTimeField()),
                ('caseNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLocation', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('district', models.CharField(choices=[('islands', 'ISLANDS'), ('kwaitsing', 'KWAI TSING'), ('north', 'NORTH'), ('saikung', 'SAI KUNG'), ('shatin', 'SHA TIN'), ('taipo', 'TAI PO'), ('tsuenwan', 'TSUEN WAN'), ('tuenmun', 'TUEN MUN'), ('yuenlong', 'YUEN LONG'), ('kowlooncity', 'KOWLOON CITY'), ('kwuntong', 'KWUN TONG'), ('shamshuipo', 'SHAM SHUI PO'), ('wongtaisin', 'WONG TAI SIN'), ('yautsimmong', 'YAU TSIM MONG'), ('centalwestern', 'CENTRAL & WESTERN'), ('eastern', 'EASTERN'), ('southern', 'SOUTHERN'), ('wanchai', 'WANCHAI')], max_length=17)),
                ('xCoord', models.IntegerField()),
                ('yCoord', models.IntegerField()),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
                ('details', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('residence', 'RESIDENCE'), ('workplace', 'WORKPLACE'), ('visit', 'VISIT'), ('other', 'OTHER')], max_length=9)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans_19.Patient', unique=True)),
            ],
        ),
    ]
