# Generated by Django 3.0.6 on 2020-05-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chp_staff_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='User name')),
                ('chp_staff_number', models.CharField(max_length=30, verbose_name='chp_staff_number')),
                ('epidemiologist_number', models.CharField(max_length=30, verbose_name='epidemiologist_number')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Location Visited')),
                ('address', models.CharField(max_length=70)),
                ('district', models.CharField(choices=[('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Islands', 'Islands'), ('Kowloon City', 'Kowloon City'), ('Kwai Tsing', 'Kwai Tsing'), ('Kwun Tong', 'Kwun Tong'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Sham Shui Po', 'Sham Shui Po'), ('Southern', 'Southern'), ('Tai Po', 'Tai Po'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun', 'Tuen Mun'), ('Wan Chai', 'Wan Chai'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Yuen Long', 'Yuen Long')], max_length=17)),
                ('xCoord', models.IntegerField(verbose_name='X Coordinate')),
                ('yCoord', models.IntegerField(verbose_name='Y Coordinate')),
                ('category', models.CharField(choices=[('residence', 'Residence'), ('workplace', 'Workplace'), ('visit', 'Visit'), ('other', 'OTHER')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('idNum', models.CharField(max_length=10, verbose_name='ID Number')),
                ('dateBirth', models.DateField(verbose_name='Date of Birth(YYYY-MM-DD)')),
                ('dateConfi', models.DateField(verbose_name='Date of Confirmation(YYYY-MM-DD)')),
                ('caseNum', models.IntegerField(verbose_name='Case Number')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_From', models.DateField(verbose_name='Date From (YYYY-MM-DD)')),
                ('date_To', models.DateField(verbose_name='Date To (YYYY-MM-DD)')),
                ('details', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('residence', 'Residence'), ('workplace', 'Workplace'), ('visit', 'Visit'), ('other', 'OTHER')], max_length=9)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans_19.Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans_19.Patient')),
            ],
        ),
    ]
