# Generated by Django 3.0.4 on 2020-04-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='idNum',
            field=models.CharField(max_length=7),
        ),
    ]
