# Generated by Django 3.0.4 on 2020-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0003_auto_20200402_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='dateFrom',
            new_name='date_From',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='dateTo',
            new_name='date_To',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='nameLocation',
            new_name='name_Location',
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('residence', 'Residence'), ('workplace', 'Workplace'), ('visit', 'Visit'), ('other', 'OTHER')], max_length=9),
        ),
        migrations.AlterField(
            model_name='case',
            name='district',
            field=models.CharField(choices=[('centalwestern', 'Central & Western'), ('eastern', 'Eastern'), ('islands', 'Islands'), ('kowlooncity', 'Kowloon City'), ('kwaitsing', 'Kwai Tsing'), ('kwuntong', 'Kwun Tong'), ('north', 'North'), ('saikung', 'Sai Kung'), ('shatin', 'Sha Tin'), ('shamshuipo', 'Sham Shui Po'), ('southern', 'Southern'), ('taipo', 'Tai Po'), ('tsuenwan', 'Tsuen Wan'), ('tuenmun', 'Tuen Mun'), ('wanchai', 'Wan Chai'), ('wongtaisin', 'Wong Tai Sin'), ('yautsimmong', 'Yau Tsim Mong'), ('yuenlong', 'Yuen Long')], max_length=17),
        ),
    ]
