# Generated by Django 3.0.4 on 2020-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0008_auto_20200424_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateBirth',
            field=models.DateField(verbose_name='Date of Birth(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateConfi',
            field=models.DateField(verbose_name='Date of Confirmation(YYYY-MM-DD)'),
        ),
    ]
