# Generated by Django 3.0.4 on 2020-04-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0009_auto_20200424_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Visit',
        ),
    ]
