# Generated by Django 3.0.5 on 2020-05-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0010_auto_20200425_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Location Visited')),
                ('address', models.CharField(max_length=70)),
                ('district', models.CharField(choices=[('centalwestern', 'Central & Western'), ('eastern', 'Eastern'), ('islands', 'Islands'), ('kowlooncity', 'Kowloon City'), ('kwaitsing', 'Kwai Tsing'), ('kwuntong', 'Kwun Tong'), ('north', 'North'), ('saikung', 'Sai Kung'), ('shatin', 'Sha Tin'), ('shamshuipo', 'Sham Shui Po'), ('southern', 'Southern'), ('taipo', 'Tai Po'), ('tsuenwan', 'Tsuen Wan'), ('tuenmun', 'Tuen Mun'), ('wanchai', 'Wan Chai'), ('wongtaisin', 'Wong Tai Sin'), ('yautsimmong', 'Yau Tsim Mong'), ('yuenlong', 'Yuen Long')], max_length=17)),
                ('xCoord', models.IntegerField(verbose_name='X Coordinate')),
                ('yCoord', models.IntegerField(verbose_name='Y Coordinate')),
                ('category', models.CharField(choices=[('residence', 'Residence'), ('workplace', 'Workplace'), ('visit', 'Visit'), ('other', 'OTHER')], max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='district',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='name_Location',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='xCoord',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='yCoord',
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_From',
            field=models.DateField(verbose_name='Date From (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_To',
            field=models.DateField(verbose_name='Date To (YYYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans_19.Location'),
        ),
    ]
