# Generated by Django 3.0.6 on 2020-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0012_auto_20200507_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='chp_staff_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='User name')),
                ('chp_staff_number', models.CharField(max_length=30, verbose_name='chp_staff_number')),
            ],
        ),
    ]
