# Generated by Django 3.0.6 on 2020-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_19', '0013_chp_staff_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chp_staff_data',
            name='epidemiologist_number',
            field=models.CharField(default=0, max_length=30, verbose_name='epidemiologist_number'),
            preserve_default=False,
        ),
    ]
