# Generated by Django 3.0.4 on 2020-04-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chpstaff', '0002_auto_20200404_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='chpStaffNumber',
            new_name='chp_staff_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
