# Generated by Django 3.0.4 on 2020-04-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chpstaff', '0004_auto_20200405_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='staff',
        ),
    ]
