# Generated by Django 3.0.4 on 2020-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpstaff', '0006_auto_20200405_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='epidemiologist',
            field=models.BooleanField(default=False),
        ),
    ]
