# Generated by Django 3.0.4 on 2020-04-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chpstaff', '0008_auto_20200407_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='epidemiologist',
        ),
    ]
