# Generated by Django 3.0.4 on 2020-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpstaff', '0009_remove_account_epidemiologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='chp_staff_number',
            field=models.CharField(max_length=7, verbose_name='CHP Staff Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password2',
            field=models.CharField(max_length=30, verbose_name='Re-Enter Your Password'),
        ),
    ]
