# Generated by Django 3.0.4 on 2020-04-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chpstaff', '0010_auto_20200424_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
